### ISSUE TITLE
Using virtual environment

### ISSUE THREAD

**Issue by avinassh** [captn3m0/google-sre-ebook#1]
I wanted to send a PR which uses Python3 `venv` to create a virtual environment to run the script. Currently the `bootstrap.sh` script tries to install in global site packages. Then I saw a dependency of pypub, which is python 2 only, so we cannot use `venv` (which is python3 only and can create python 3 virtual environments).

So I have 2 solutions:

1. Leave it as it as, but update readme to reflect that it uses Python 2 and run bootstrap.sh in a Python2 venv
2. Use `virtualenv`. But this adds one external dependency. But then, I assume almost everyone has this installed.

What do you say? 🤓

**Comment by captn3m0** [comment]
I did setup a venv locally before realizing it was python 2 only. Will add a warning.
