### ISSUE TITLE
can we use alpine or smaller instance

### ISSUE THREAD

**Issue by jethroguce** [captn3m0/google-sre-ebook#16]
the docker image i believe  is too large for a single run, i think it would be better to convert the docker base image to smaller instance

**Comment by captn3m0** [comment]
I'm a big fan of smaller docker images (especially Alpine), and use them wherever I can. I did attempt switching to Alpine for this, but getting pandoc and calibre to work properly on alpine is not worth the effort.

I'm still open to PRs though.

**Comment by mahmoudhossam** [comment]
@captn3m0 I was able to get pandoc to run in Alpine, but not Calibre since they only provide binaries using glibc (Alpine uses musl).

Can't we just use pandoc to convert to mobi and pdf and drop the Calibre dependency?

**Comment by captn3m0** [comment]
Pandoc doesn't do mobi, and PDFs require a latex-engine to be installed for pandoc. Still open to PRs if you can get all 3 generated without calibre.

We can use `kindlegen`, but distributing it might in a [docker image might break their license](https://www.amazon.com/gp/feature.html?docId=1000599251).

Another solution I was considering was switching to `debian:slim`. Going to give that a try.

**Comment by captn3m0** [comment]
Another solution might be to have 2 dockerfiles, the Alpine one for a limited EPUB / PDF using pandoc and the larger one in case you need mobi files.

**Comment by captn3m0** [comment]
So debian turned out to be not-so-great idea (image size grew slightly, likely because of a ruby upgrade)

![image](https://user-images.githubusercontent.com/584253/51323608-ad7f7380-1a8e-11e9-83bc-2c2112657e65.png)

If you can file a PR with a `epub.Dockerfile` built against Alpine I'll merge it and setup auto-builds.

**Comment by mahmoudhossam** [comment]
@captn3m0 I created a pull request with the epub dockerfile, check it out.

**Comment by captn3m0** [comment]
Decided against this, too much of a pain to maintain.
