### ISSUE TITLE
SRE Workbook Availability (now)

### ISSUE THREAD

**Issue by kingdonb** [captn3m0/google-sre-ebook#19]
I just read that the SRE Workbook is now similarly available to read online:

https://landing.google.com/sre/books/

That means that BOTH books can be converted with pandoc, great idea by the way!  My eyesight thanks you, I need to read these books but I don't need more screen time every day...

I'll take a stab at it?  Been meaning to grok how this works, so I can repurpose it and use it for WTF other collections of essays I want to read offline.  Adapting it to work on exactly one more identically structured book publication should help gain the insight needed to use this technique for other blog-format sites.

I noticed that "mobi" output does not have images, but epub and PDF both do.  Is this a technical limitation of mobi format, or pandoc issue?  Thanks,

**Comment by captn3m0** [comment]
Sounds good, have a stab at it!

Repurposing online essays/books to ebooks is a hobby of mine, and I have some interesting links at https://captnemo.in/ebooks/ that you might like.

The mobi thing sounds like a bug, should not be happening.

**Comment by aabouzaid** [comment]
The mobi version doesn't have images because the images in Workbook are in `png` format unlike the old book (Engineering) which were `jpg`.

mobi doesn't support png images.

**Comment by aabouzaid** [comment]
Well, after further investigation, I found the image type is not the problem (that was something with old version of mobi and/or kindle devices).

The problem actually is `pandoc` cannot get the right file `mime type` [with no file extension](https://github.com/jgm/pandoc/issues/1855) (all images are without extensions even in the old book).

So this happens for both books SRE Engineering and SRE Workbook and not something new.
The easiest solution for this is just adding the file extension based on file type.

I'm working on a fix for this and will make a PR.

**Comment by kingdonb** [comment]
#21 closes this issue
