### ISSUE TITLE
pandoc: unrecognized option `--pdf-engine=xelatex'

### ISSUE THREAD

**Issue by icycle77** [captn3m0/google-sre-ebook#31]
Using Docker as follows:

`docker run --rm --volume "$(pwd):/output" -e BOOK_SLUG='sre_book' captn3m0/google-sre-ebook:latest`

Output looks good until 
```
Generate book ...
/usr/lib/ruby/vendor_ruby/rubygems/defaults/operating_system.rb:10: warning: constant Gem::ConfigMap is deprecated
/usr/lib/ruby/vendor_ruby/rubygems/defaults/operating_system.rb:10: warning: constant Gem::ConfigMap is deprecated
/usr/lib/ruby/vendor_ruby/rubygems/defaults/operating_system.rb:29: warning: constant Gem::ConfigMap is deprecated
/usr/lib/ruby/vendor_ruby/rubygems/defaults/operating_system.rb:30: warning: constant Gem::ConfigMap is deprecated
/usr/lib/ruby/vendor_ruby/rubygems/defaults/operating_system.rb:10: warning: constant Gem::ConfigMap is deprecated
/usr/lib/ruby/vendor_ruby/rubygems/defaults/operating_system.rb:10: warning: constant Gem::ConfigMap is deprecated
/usr/lib/ruby/vendor_ruby/rubygems/defaults/operating_system.rb:10: warning: constant Gem::ConfigMap is deprecated
/usr/lib/ruby/vendor_ruby/rubygems/defaults/operating_system.rb:10: warning: constant Gem::ConfigMap is deprecated
/usr/lib/ruby/vendor_ruby/rubygems/defaults/operating_system.rb:10: warning: constant Gem::ConfigMap is deprecated
/usr/lib/ruby/vendor_ruby/rubygems/defaults/operating_system.rb:29: warning: constant Gem::ConfigMap is deprecated
/usr/lib/ruby/vendor_ruby/rubygems/defaults/operating_system.rb:30: warning: constant Gem::ConfigMap is deprecated
/usr/lib/ruby/vendor_ruby/rubygems/defaults/operating_system.rb:10: warning: constant Gem::ConfigMap is deprecated
/usr/lib/ruby/vendor_ruby/rubygems/defaults/operating_system.rb:10: warning: constant Gem::ConfigMap is deprecated
/usr/lib/ruby/vendor_ruby/rubygems/defaults/operating_system.rb:10: warning: constant Gem::ConfigMap is deprecated
[html] Generated HTML file
/src/html/landing.google.com/sre/sre-book/toc /src
pandoc: unrecognized option `--pdf-engine=xelatex'
Try pandoc --help for more information.
```

Version info from the output:
```
Digest: sha256:9e6fe8db057e159733c42d73e18f6b2befe4d8176c7ee49ec73468c8ee92d20a
Status: Downloaded newer image for captn3m0/google-sre-ebook:latest
```

**Comment by davic80** [comment]
Same issue, login into the container and pandoc version is:
# pandoc --version
pandoc 1.19.2.4
Compiled with pandoc-types 1.17.0.5, texmath 0.9.4.4, skylighting 0.3.3.1
Default user data directory: /root/.pandoc
Copyright (C) 2006-2016 John MacFarlane
Web:  http://pandoc.org
This is free software; see the source for copying conditions.
There is no warranty, not even for merchantability or fitness
for a particular purpose.
#

**Comment by rusik69** [comment]
+1 in docker image

**Comment by diegolmoreno** [comment]
It happens on Ubuntu bionic because the pandoc's repo version is 1.19. pdf-engine was introduced on pandoc 1.20. Possible workarounds:

- If the pdf file is not needed then comment the pandoc command to generate pdf from html on file generate.sh and rebuild the container: ```docker build -t <new_image_tag> .```

or alternatively:

- Set a different repo on Ubuntu for pandoc so the pandoc version has that option (not tried)

**Comment by captn3m0** [comment]
I'd put the generated PDF version on releases: https://github.com/captn3m0/google-sre-ebook/releases for issues like these.

The pandoc PDF is so much more better in typesetting that I really want to keep this, will see if I can get the Docker image functional again (and add tests)

**Comment by rusik69** [comment]
i've hacked a working solution together, #32 . you can use it as an inspiration for a real fix :)

**Comment by captn3m0** [comment]
Thanks a lot everyone, managed to fix this by switching to debian packages and installing a few extra deps. :100: 

It's still not perfect (cover images are missing, tables aren't formatted well etc - but its wayy better than the previous versions)
