### ISSUE TITLE
Configurable font size in PDF

### ISSUE THREAD

**Issue by pgillich** [captn3m0/google-sre-ebook#77]
It would be useful, if the font size can be configurable in exported PDF. The command line in `generate.sh` looks like:

```sh
pandoc --from=html \
(...)
    -V documentclass=extbook \
    -V fontsize=14pt \
    --columns=60 \
    complete.html
```

The font size can be an optional environment variable, like `BOOK_SLUG`.

Only a few font sizes are supported by `extbook`: 8pt, 9pt, 10pt, 11pt, 12pt, 14pt, 17pt, and 20pt, see <https://www.ctan.org/tex-archive/macros/latex/contrib/extsizes>.

**Comment by captn3m0** [comment]
Sounds good. Happy to accept PRs for this.

**Comment by pgillich** [comment]
> Sounds good. Happy to accept PRs for this.

OK, I'll do it next days.
