### ISSUE TITLE
Resolving landing.google.com (landing.google.com)... failed: Temporary failure in name resolution.

### ISSUE THREAD

**Issue by suryastef** [captn3m0/google-sre-ebook#9]
suryastef  ~  `docker run --rm --volume "$(pwd):/output" captn3m0/google-sre-ebook:latest`

> --2018-07-26 05:28:44--  https://landing.google.com/sre/book/
> Resolving landing.google.com (landing.google.com)... failed: Temporary failure in name resolution.
> wget: unable to resolve host address 'landing.google.com'
> Converted links in 0 files in 0 seconds.
> mv: cannot stat 'landing.google.com/sre/book/*': No such file or directory
> generate.rb:6:in `initialize': No such file or directory @ rb_sysopen - html/index.html (Errno::ENOENT)
> 	from generate.rb:6:in `open'
> 	from generate.rb:6:in `<main>'
> /src/bootstrap.sh: line 20: pushd: html/chapters: No such file or directory
> pandoc: ../../metadata.xml: openFile: does not exist (No such file or directory)
> /src/bootstrap.sh: line 22: popd: directory stack empty
> Cannot read from /src/google-sre.epub
> chown: cannot access 'google-sre.*': No such file or directory
> failed to change ownership of 'google-sre.*' to 0:0
> mv: cannot stat 'google-sre.*': No such file or directory
>

**Comment by captn3m0** [comment]
This is a fairly common docker issue. Please check your docker version, and if you've recently upgraded your kernel, a reboot might help.

Can you once try adding `--dns=1.1.1.1` to your run command and see if it works?

**Comment by captn3m0** [comment]
Closing
